### ISSUE TITLE
How to access express if the token has been renewed?

### ISSUE THREAD

**Issue by LucasLauDev** [num8er/express-access-token#4]
const token = JSON.parse(fs.readFileSync('./XinRuiAPI/token.json', 'utf8'));
const firewall = (req, res, next) => {
  const authorized = token.includes(req.query.token);
  if(!authorized) return res.status(403).send({ status: "failed", error: "403 Forbidden", message: "此API为付费节点", token: token });
  next();
};

**Comment by LucasLauDev** [comment]
I cannot restart my API everytime when someone's token has been just renewed because it will effect the API 's uptime
so `I use const token = JSON.parse(fs.readFileSync('./XinRuiAPI/token.json', 'utf8'));`
but it seem cannot work.

**Comment by num8er** [comment]
> I cannot restart my API everytime when someone's token has been just renewed because it will effect the API 's uptime
> so `I use const token = JSON.parse(fs.readFileSync('./XinRuiAPI/token.json', 'utf8'));`
> but it seem cannot work.

Your issue is not related to middleware.
You've to question Yourself how to watch changes and reload it.

So here is an example:

```js
const  fs = require('fs');
const fsp = require('fs/promises');

class TokenStorage {
  constructor(pathsToTokensFile) {
    this._tokensFile = pathsToTokensFile;
    this._tokens = new Set();
    this._loadFile().then(() => {});
    this._watchFile();
  }

  async _loadFile() {
    try {
      let tokens = await fsp.readFile(this._tokensFile);
      tokens = JSON.parse(tokens.toString('utf8'));
      if (Array.isArray(tokens)) {
        this._tokens = new Set(tokens);
      }
    }
    catch(error) {
      console.error(`Cannot parse ${this._tokensFile}. Reason: ${error.message}`);
    }
  }
  
  _watchFile() {
    fs.watchFile(this._tokensFile, async () => {
      console.log(`${this._tokensFile} has been changed. Reloading.`);
      await this._loadFile();
    });
  }

  has(token) {
    return this._tokens.has(token);
  }
}

const tokens = new TokenStorage(__dirname + '/XinRuiAPI/token.json');

const firewall = (req, res, next) => {
  const authorized = tokens.has(req.query.token);
  if(!authorized) {
    return res.status(403).send({ status: "failed", error: "403 Forbidden", message: "此API为付费节点", token: token });
  }
  next();
};
```

**Comment by QC-Development** [comment]
UnhandledPromiseRejectionWarning: TypeError: this.loadFile is not a function

**Comment by LucasLauDev** [comment]
**Update**: 
**if nodeJS version is 12.x**, should be like this: `const fsp = require('fs').promises;`

**In line 28**:
`await this.loadFile();` must change to `await this._loadFile();`

**Comment by num8er** [comment]
> **Update**: 
> 
> **if nodeJS version is 12.x**, should be like this: `const fsp = require('fs').promises;`
> 
> 
> 
> **In line 28**:
> 
> `await this.loadFile();` must change to `await this._loadFile();`

I wrote that code from phone without IDE, it's possible that I can make mistakes)))

So overall, have You reached Your expectations? ;)
